# Generated by Django 5.1.3 on 2024-11-23 16:20

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_song_album_song_lyrics_delete_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='aka',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artist',
            name='cover_picture',
            field=models.ImageField(blank=True, null=True, upload_to='artist_covers/'),
        ),
    ]
