# Generated by Django 5.1.3 on 2024-11-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.CharField(blank=True, choices=[('rap', 'Rap'), ('pop', 'Pop'), ('rnb', 'R&B'), ('country', 'Country'), ('rock', 'Rock')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.CharField(blank=True, choices=[('rap', 'Rap'), ('pop', 'Pop'), ('rnb', 'R&B'), ('country', 'Country'), ('rock', 'Rock')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, choices=[('rap', 'Rap'), ('pop', 'Pop'), ('rnb', 'R&B'), ('country', 'Country'), ('rock', 'Rock')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
