# Generated by Django 5.1.3 on 2024-12-01 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_song_cover_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='cover_photo',
            new_name='song_cover',
        ),
    ]
