# Generated by Django 5.1.3 on 2024-12-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_cover_photo_song_song_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='detailed_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
