# Generated by Django 5.1.3 on 2024-12-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='video',
            name='embed_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
