# Generated by Django 5.1.3 on 2024-12-10 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_video_youtube_url_video_embed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.artist'),
        ),
    ]
