# Generated by Django 5.1.3 on 2024-12-14 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_video_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='LyricLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_text', models.TextField()),
                ('timestamp', models.TimeField(help_text='Time when the line starts in the song (HH:MM:SS)')),
                ('meaning', models.TextField(blank=True, help_text='Optional: Explanation or meaning of the lyric', null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyric_lines', to='myapp.song')),
            ],
        ),
    ]
