# Generated by Django 5.1.4 on 2024-12-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_lyricline'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='crop_coords',
            field=models.CharField(blank=True, help_text="Enter crop coordinates as 'left,upper,right,lower' (e.g., 100,50,800,600). Leave blank for default cropping.", max_length=50, null=True),
        ),
    ]
