# Generated by Django 5.1.4 on 2024-12-28 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_artist_crop_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='soundcloud',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='spotify',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
