# Generated by Django 5.1.4 on 2024-12-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_artist_instagram_artist_soundcloud_artist_spotify_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='telegram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
