# Generated by Django 5.1.4 on 2024-12-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_artist_monthly_listeners_song_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='monthly_listeners',
            field=models.IntegerField(default=0),
        ),
    ]
