# Generated by Django 5.1.4 on 2025-01-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_song_popularity_remove_song_spotify_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyricline',
            name='meaning',
        ),
        migrations.AddField(
            model_name='lyricline',
            name='is_highlighted',
            field=models.BooleanField(default=False, help_text='Set to True if the line has a meaning.'),
        ),
        migrations.AlterField(
            model_name='lyricline',
            name='timestamp',
            field=models.TimeField(blank=True, help_text='Time when the line starts in the song (HH:MM:SS)', null=True),
        ),
        migrations.CreateModel(
            name='LyricMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meaning_text', models.TextField(help_text='Explanation or meaning of the selected lyrics.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lyric_lines', models.ManyToManyField(help_text='Select lyric lines for this meaning.', related_name='meanings', to='myapp.lyricline')),
            ],
        ),
    ]
