# Generated by Django 5.1.4 on 2025-01-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_lyricline_meaning_lyricline_is_highlighted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lyricline',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='song',
            name='lyrics',
        ),
    ]
