name: Django CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: myradifuser
          POSTGRES_PASSWORD: myradifpassword
          POSTGRES_DB: myradifdb
        ports:
          - 5432:5432

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Migrations
        env:
          DATABASE_URL: postgres://myradifuser:myradifpassword@localhost:5432/myradifdb
        run: |
          python manage.py migrate

      - name: Run Tests
        env:
          DATABASE_URL: postgres://myradifuser:myradifpassword@localhost:5432/myradifdb
        run: |
          python manage.py test